import {readFileSync} from "node:fs";
import path from "node:path";
import pg from "pg";
import type {ParsedXuequzhushou,SourceSchool} from "../../lib/ingest/xuequzhushou";

const databaseUrl=process.env.DATABASE_URL;
if(!databaseUrl)throw new Error("DATABASE_URL is required");
const snapshotPath=path.join(process.cwd(),"data/ingest/xuequzhushou/20260711-035825/parsed.json");

async function main(){const parsed=JSON.parse(readFileSync(snapshotPath,"utf8")) as ParsedXuequzhushou;const client=new pg.Client({connectionString:databaseUrl});await client.connect();try{await client.query("BEGIN");await client.query(readFileSync(path.join(process.cwd(),"db/redesign/004_create_source_schools.sql"),"utf8").replace(/^BEGIN;|COMMIT;$/gm,""));for(const district of parsed.districtOrder){for(const [schoolType,schools] of [["primary",parsed.districts[district].小学??[]],["middle",parsed.districts[district].初中??[]]] as const){for(const school of schools as SourceSchool[]){const sourceKey=`${district}:${schoolType}:${school.名称}`;const {rows}=await client.query<{id:string}>(`select catalog_entity_id id from audit.entity_match_candidates m join ingest.extracted_records e on e.id=m.source_record_id where e.source_key=$1 and m.status in ('accepted','suggested') order by m.match_score desc limit 1`,[sourceKey]);await client.query(`insert into catalog.source_schools(source_key,source_name,source_url,source_year,district,school_name,school_type,tier,area,street,feeder_middle_school,middle_school_tier,evaluation,admission_mode,class_count,tags,lng,lat,catalog_school_id,attrs) values($1,'学区助手',$2,2026,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14::jsonb,$15,$16,$17,$18::jsonb) on conflict(source_key) do update set tier=excluded.tier,area=excluded.area,street=excluded.street,feeder_middle_school=excluded.feeder_middle_school,middle_school_tier=excluded.middle_school_tier,evaluation=excluded.evaluation,admission_mode=excluded.admission_mode,class_count=excluded.class_count,tags=excluded.tags,lng=excluded.lng,lat=excluded.lat,catalog_school_id=excluded.catalog_school_id,attrs=excluded.attrs,updated_at=now()`,[sourceKey,parsed.sourceUrl,district,school.名称,schoolType,school.梯队??null,school.片区??null,school.街道??null,school.对口初中??null,school.初中梯队??null,school.评价??null,school.入学方式??null,school.招生班级??null,JSON.stringify(school.标签??[]),school.lng??null,school.lat??null,rows[0]?.id??null,JSON.stringify({districtAdmissionSystem:parsed.districts[district].入学制度,districtNote:parsed.districts[district].说明})]);}}}await client.query("COMMIT");const {rows}=await client.query(`select count(*)::int total,count(*) filter(where school_type='primary')::int primary_schools,count(*) filter(where school_type='middle')::int middle_schools,count(*) filter(where lng is not null and lat is not null)::int with_coordinates,count(*) filter(where evaluation is not null)::int with_evaluation,count(*) filter(where tags<>'[]'::jsonb)::int with_tags from catalog.source_schools where source_name='学区助手'`);console.table(rows)}catch(error){await client.query("ROLLBACK");throw error}finally{await client.end()}}
main().catch(error=>{console.error(error);process.exitCode=1});
